name: Mi Primer Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Pipeline ejecutado correctamente"